name: Deploy Chinese Antique Website

#run-name denoted by commit name in triggered push
on:
  push:
    branches:
      - main

jobs:
  deploy:
    #runner that once completed, gets a new clean state and turns off. Hence, 'runner'
    #implications: nothing is stored
    runs-on: ubuntu-latest 
    steps:
      - name: Deploy Project
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/yangantiques.com/chinese-antiques-website

            git fetch -all
            git reset --hard origin/main

            #Install dependencies (if needed - clean install)
            npm ci

            #optimized version
            npm run build

            pm2 restart nextjs-app  

          
      





      

          
      





          
      




